### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by notthetup** [kylestetz/AudioKeys#1]
Would be great to be able to install this through npm `npm install --save audiokeys`. 

Since your `package.json` is already setup, all you'd need to do is 'npm publish'

**Comment by notthetup** [comment]
DOH! Totally overlooked the fact that you'd need to add support for something like browserify. Sorry. If this is too much of a change feel free to close this issue :(

**Comment by kylestetz** [comment]
Two years later... ✅
