### ISSUE TITLE
Up events have same velocity as down events

### ISSUE THREAD

**Issue by 0x80** [kylestetz/AudioKeys#2]
Is this by design or a bug? 

I am merging both into a stream, but I have to mutate the up events to have velocity 0 in order to distinguish the note off events. Maybe I'm missing something...

**Comment by kylestetz** [comment]
Sorry for the delay on this! I had my notifications turned off 😢 this is a good point, I will update the note off events to have a velocity of 0 :+1:

**Comment by 0x80** [comment]
😄no problem

**Comment by kylestetz** [comment]
Just patched this up and added a unit test for it :+1:
