### ISSUE TITLE
improvement on 2 octave kb mode

### ISSUE THREAD

**Issue by AlexPoulsen** [kylestetz/AudioKeys#3]
![68747470733a2f2f7261772e6769746875622e636f6d2f6b796c65737465747a2f617564696f6b6579732f6d61737465722f696d616765732f617564696f6b6579732d6d617070696e672d726f7773322e6a7067](https://cloud.githubusercontent.com/assets/9259671/16057573/b563d45a-3248-11e6-9c82-5400def82e4f.jpeg)
1 and/or - could increase octave and A and/or ' could decrease octave
4 and 8 could function as pitch bend or modulation up/down
F and K could decrease and increase velocity

I don't know js otherwise I'd fork and implement it myself

**Comment by kylestetz** [comment]
Sorry I missed this when you posted it! My notifications were turned off for some reason ☹️ 

This is an interesting idea but I would worry about folks hitting the wrong key while playing and changing the state of things. That said, the other keyboard layout (with only one octave) leaves a bit more room for extra controls along the bottom.

I'm not going to implement any additional state for now but I do appreciate the suggestion! 🍻
