### ISSUE TITLE
published on npm?

### ISSUE THREAD

**Issue by tambien** [kylestetz/AudioKeys#4]
Great lib. I've been using AudioKeys in a few of my projects. 

I typically install js libraries through npm, but I couldn't find it when I searched for it. Is it published on npm?

thanks!

**Comment by stephenhandley** [comment]
+1

**Comment by kylestetz** [comment]
Whoops! Somehow my notifications got turned off for this repo. Sorry y'all!! I'll take a pass at the codebase this weekend and throw it up on npm. :v:

**Comment by kylestetz** [comment]
You can now `npm install audiokeys`! Thanks for the nudge @stephenhandley 🍻

**Comment by stephenhandley** [comment]
awesome thanks @kylestetz!
